const express = require('express');
const router = express.Router();
const ordersRoutes = require('./routes/orders')
const pegawaiRoutes = require('./routes/pegawai')
const progressRoutes = require('./routes/progress')
const customerRoutes = require('./routes/customer')
const settingsRoutes = require('./routes/settings')
const authRoutes = require('./routes/auth')
const dashboardRoutes = require('./routes/dashboard')
const reportRoutes = require('./routes/reports')
const chatRoutes = require('./routes/chats')
const cashbackRoutes = require('./routes/cashback')
const slideRoutes = require('./routes/slides')
const jobdeskRoutes = require('./routes/jobdesk')
const ratingsRoutes = require('./routes/ratings')
const inventoryRoutes = require('./routes/inventory')
const checkCardRoutes = require('./routes/check-card')
const notifRoutes = require('./routes/notifikasi')

router.use('/orders', ordersRoutes)
router.use('/pegawai', pegawaiRoutes)
router.use('/progress', progressRoutes)
router.use('/customer', customerRoutes)
router.use('/settings', settingsRoutes)
router.use('/auth', authRoutes)
router.use('/dashboard', dashboardRoutes)
router.use('/reports', reportRoutes)
router.use('/chats', chatRoutes)
router.use('/cashback', cashbackRoutes)
router.use('/slides', slideRoutes)
router.use('/jobdesk', jobdeskRoutes)
router.use('/ratings', ratingsRoutes)
router.use('/inventory', inventoryRoutes)
router.use('/check-card', checkCardRoutes)
router.use('/notifikasi', notifRoutes)

module.exports = router;